[package]
name = "skillratings"
version = "0.10.2"
edition = "2021"
description = "Calculate a player's skill rating using Elo, DWZ, Ingo, TrueSkill, Glicko and Glicko-2 algorithms."
readme= "README.md"
repository = "https://github.com/atomflunder/skillratings"
license = "MIT"
keywords = ["elo", "glicko-2", "glicko", "dwz", "trueskill"]
categories = ["game-development", "algorithms", "mathematics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]