name: Rust Project CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Update rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build crate
        run: cargo build --release --verbose

      - name: Test crate
        run: cargo test --verbose

      - name: Build docs
        run: cargo doc --verbose

      - name: Publish dry run
        run: |
          cargo check --verbose
          cargo package --verbose
          cargo publish --dry-run --verbose

      - name: Run clippy
        run: |
          rustup component add clippy
          cargo clippy --workspace
